name: Build & Test

permissions:
  statuses: write
  checks: write
  pull-requests: read
  contents: read

on:
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Restore Node.js dependencies
        run: yarn install --immutable

      - name: Build nodes
        run: yarn build

      - name: Check styling
        run: yarn prettier

      - name: Check for linting errors
        run: yarn lint:ci

      - name: Annotate from ESLint report
        uses: ataylorme/eslint-annotate-action@v2
        with:
          fail-on-warning: true
